my:
  datasource:
    url: local.db.com
    username: jkpark
    password: '1234123123'
    etc:
      max-connection: '1'
      options: CACHE,ADMIN
      timeout: 3500ms
---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username: jkpark
    password: '1234123123'
    etc:
      max-connection: '1'
      options: CACHE,ADMIN
      timeout: 3500ms
---
spring:
  config:
    activate:
      on-profile: prod
my:
  datasource:
    url: prod.db.com
    username: jkpark
    password: '1234123123'
    etc:
      max-connection: '1'
      options: CACHE,ADMIN
      timeout: 3500ms